name: Tests
on:
  push:
    branches: ["**"]
  pull_request: {}
  workflow_dispatch: {}
env:
  UV_PYTHON_PREFERENCE: only-system
  UV_NO_SYNC: "1"
  PKCS11_TOKEN_LABEL: "TEST"
  PKCS11_TOKEN_PIN: "1234"
  PKCS11_TOKEN_SO_PIN: "5678"
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      # Our test suite is pretty fast, so fail-fast: false allows for better troubleshooting.
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ./.github/actions/install-softhsm
        id: softhsm
        with:
          os: ${{ matrix.os }}
          token-label: ${{ env.PKCS11_TOKEN_LABEL }}
          token-so-pin: ${{ env.PKCS11_TOKEN_SO_PIN }}
          token-user-pin: ${{ env.PKCS11_TOKEN_PIN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install testing dependencies
        run: uv sync --no-dev --exact --group testing
      - name: Run tests
        run: uv run pytest -v
        env:
          PKCS11_MODULE: ${{ steps.softhsm.outputs.module }}